name: Checkmarx One Scan
on:
  push:
    branches:
      - main
      - master
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Set SCA Resolver Environment
        run: "wget -q https://sca-downloads.s3.amazonaws.com/cli/latest/ScaResolver-musl64.tar.gz && tar -xzvf ScaResolver-musl64.tar.gz && rm -rf ScaResolver-musl64.tar.gz && chmod 777 ./ScaResolver && pwd && ls -la"
      - name: Checkmarx One CLI Action
        uses: checkmarx/ast-github-action@main #Github Action version
        with:
          project_name: CxFlowGithub
          cx_tenant: ${{ secrets.CX_TENANT }}
          base_uri: ${{ secrets.CX_BASE_URI }}
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          additional_params: --scan-types sca
                             --sca-resolver "./ScaResolver"
                             --sca-resolver-params "--log-level Debug"
                             --debug 
