# Controls when the action will run. Triggers the workflow on push or pull request or on schedule
# * is a special character in YAML so you have to quote this string
# Everyday each 5 minutes
name: "Checkmarx SAST Scan - Manual - JIRA"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkmarx CxFlow Action
      uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.1 #Github Action version
      with:
        project: test-manual
        team: '/CxServer'
        checkmarx_url: ${{ secrets.CX_SERVER }}
        checkmarx_username: ${{secrets.CX_USER}}
        checkmarx_password: ${{secrets.CX_PASSWD}}
        checkmarx_client_secret: ${{secrets.CX_CLIENT_SECRET}}        
        preset: 'High and Medium'
        # app: CxFlowGitHub
        # Break build based on Checkmarx findings?
        #break_build: # optional
        incremental: false
        scanners: sast
        bug_tracker: JIRA
        params: '--cx-flow.bug-tracker-impl=JIRA --checkmarx.settings-override=true --namespace=${{ github.repository_owner }} --repo-name=${{ github.event.repository.name }} --branch=${{ github.ref }} --cx-flow.filter-severity=high --cx-flow.filter-category=SQL_Injection --logging.level.com.checkmarx.flow.service=debug --logging.level.com.checkmarx.flow.utils=debug --logging.level.com.checkmarx.sdk.service=debug --jira.url=${{ secrets.JIRA_URL }} --jira.username=${{ secrets.JIRA_USER }} --jira.token=${{ secrets.JIRA_TOKEN }} --jira.project=${{ secrets.JIRA_PROJECT }} --jira.issue-type=Bug --jira.priorities.High=High --jira.priorities.Medium=Medium --jira.priorities.Low=Low --jira.priorities.Informational=Lowest --jira.open-transition="In Progress" --jira.close-transition=Done --jira.open-status=Backlog,"Selected for Development",In Progress --jira.closed-status=Done --jira.fields.0.type=static --jira.fields.0.name=epiclink --jira.fields.0.jira-field-name="Epic Link" --jira.fields.0.jira-field-type=text --jira.fields.0.jira-default-value=APPSEC-435'
        # github_token: ${{secrets.GITHUB_TOKEN}}
#         extra parameter
#         params: --cx-flow.filter-status="New" --bug-tracker=jira --config=cx.config --repo-
#         name=Orderweb --namespace= --branch=master --jira.url=${{secrets.JIRA_URL}} --jira.username=${{secrets.JIRA_USER}} --jira.
#         token=${{secrets.JIRA_TOKEN}} --forcescan=true
##    - name: Upload SARIF file
##      uses: github/codeql-action/upload-sarif@v1
##      with:
##        sarif_file: cx.sarif
